Add `types` fields to exports
TypeScript 4.7 introduced `node16` and `nodenext` values for its
`moduleResolution` setting, and version 5.0 introduced `bundler`. These
mimic Node.js's module resolution and result in TypeScript looking at
the `exports` keys in `package.json`. This is then also where it looks
for `types`, rather than at the top level. Hence, this adds the relevant
references to types there, to avoid errors like

    Type error: Cannot find module 'dotenv-flow/config' or its
    corresponding type declarations.

for importers of this library with that `moduleResolution` setting.

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#packagejson-exports-imports-and-self-referencing